---
# tasks file for tomcatinstall
- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: yes

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install Default Java (Debian/Ubuntu)
  apt:
    name: default-jdk
    state: present

- name: Create group 'tomcat'
  group:
    name: tomcat
    state: present

- name: Add "tomcat" user
  user:
    name: tomcat
    group: tomcat
    home: /opt/tomcat
    createhome: no
    shell: /bin/false
    system: yes


- name: Download Tomcat
  get_url:
    url: "{{ tomcat_archive_url }}"
    dest: "{{ tomcat_archive_dest }}"

- name: Creates directory
  ansible.builtin.file:
    path: /opt/tomcat
    state: directory
    owner: tomcat
    group: tomcat
    mode: 0775

- name: Extract tomcat archive
  unarchive:
    src: "{{ tomcat_archive_dest }}"
    dest: /opt/tomcat
    owner: tomcat
    group: tomcat
    remote_src: yes
    extra_opts: "--strip-components=1"
    creates: /opt/tomcat/bin

- name: Copy tomcat service file
  template:
    src: templates/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
#  when: ansible_service_mgr == "systemd"


- name: Start and enable tomcat
  service:
    daemon_reload: yes
    name: tomcat
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"
  notify: restart tomcat
